services:
  exercisediary:
    image: ghcr.io/kraleod/exercisediary:latest
    restart: unless-stopped
    ports:
      - 8851:8851
    volumes:
      - ./data:/data/ExerciseDiary
    environment:
      TZ: Europe/Berlin
      PORT: "8851"
      HOST: "0.0.0.0"
