services:
  exercisediary:
    image: ghcr.io/kraleod/exercisediary:latest
    restart: unless-stopped
    ports:
      - 8852:8852
    volumes:
      - ./data:/data/ExerciseDiary
    environment:
      TZ: Europe/Berlin
      PORT: "8852"
#      HOST: "0.0.0.0"
