services:
  exercisediary:
    build: .
    restart: unless-stopped
    ports:
      - 8851:8851
    volumes:
      - ~/.dockerdata/ExerciseDiary:/data/ExerciseDiary
    environment:
      TZ: Europe/Berlin
      PORT: "8851"
      HOST: "0.0.0.0"
